# Generated by Django 3.2.25 on 2024-10-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgfinance', '0003_usercollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
